# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Head info
head:
    favicon: "/img/logo_miccall_self.jpg"
    keywords: miccall
    backgroundpic : "img/bg.jpg"

Intro:
    name: Sharing Little Bai
    slogan: "当你发现你失败时<br/>你就已经走在了成功的路上"
    HeadButton: 现在开始

Nav:
    Home_name: 主页
    is_use_categories : true 
    categories_name: 分类
    is_use_archives : false
    archives_name: 归档
    
    #Social
    # for more icons, please see http://fontawesome.io/icons/#brand
    icon:
        jianshu: https://www.jianshu.com/u/ed203e2f5403
        github: https://github.com/LittleCCB
        csdn: https://blog.csdn.net/qq_43592084
        
    pages:
        简历: 
            link: "/about/"
        #团队 :
        #    link: "/group/"
        图库 :
            link: "/gallery/"
        标签:
            link: "/tag/"
        #自定义标签名
        #管理:
        #   link："/admin/"

MainFirst:
    name: 想法+创意
    description: Welcome to my Blog   
    pic_url: /images/me.jpg
    goto_ulr: "/about/"

Gallery :
    title: 白先生 
    description: 似曾相识燕归来 

# ---------------------------------------------------------------
# Style Settings
# ---------------------------------------------------------------

# Custom code Render System 自定义代码渲染 
# default dark funky okaidia twilight coy solarized  可选项  
# link to review : http://prismjs.com/index.html   官网预览
prism: coy

# Custom Fonts
fonts: FZLTCXHJW, "Helvetica Neue", Helvetica, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "FZLTCXHJW", Arial, sans-serif

# Comment Systems
# Available value of "use":
#     duoshuo | disqus | disqus_click | changyan
comment:
    use: disqus_click
    shortname: http-miccall-tech 
    duoshuo_thread_key_type: path
    duoshuo_embed_js_url: "https://static.duoshuo.com/embed.js"
    changyan_appid:
    changyan_conf:
    changyan_thread_key_type: path
    # 使用 valine 请先执行 npm install valine --save
    valine: # Valine Comment System https://github.com/xCss/Valine
       on: false
       appId: 'bQ6F9e3Gp3pOhlvGiYncmhoi-gzGzoHsz'
       appKey: 'a8km9xDijKXKIuJhJi2uDtRb'
       notify: true
       verify: false
       placeholder: Please leave your footprints
       avatar: ''
       avatar_cdn: https://gravatar.loli.net/avatar/ # avatar CDN address, default gravatar.loli.net
       pageSize: 10 # comments of one page

# Search Systems
# Available value:
#     swiftype | google | local
search:
    use: google
    swiftype_key: Just another fine responsive  
    

# Leancloud Views
leancloud:
    enable: false
    app_id: bQ6F9e3Gp3pOhlvGiYncmhoi-gzGzoHsz
    app_key: a8km9xDijKXKIuJhJi2uDtRb
    av_core_mini: "https://cdn1.lncld.net/static/js/av-core-mini-0.6.1.js"

# Busuanzi 不蒜子 Views
busuanzi:
    enable: false
    all_site_uv: true
    post_pv: true
    busuanzi_pure_mini_js: "https://dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js"


# Mathjax 支持库 
mathjax:
  enable: true
  per_page: false
  cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML